module My_types exposing (..)
import Http
import Html exposing ( Html, Attribute, main_,  span, a, p, img ,br, text, strong, option, small, input, i , select, label)
import Html.Attributes exposing ( attribute, style, src, placeholder, type_, href, rel, class , value, selected)
import Html.Events exposing (onClick, on)
import Html.Events.Extra exposing (targetValueIntParse)
import Json.Decode as Json

type Model 
  =  Failure
  | Loading
  | Loaded WorldHappData

type Msg
  = GotText (Result Http.Error String)
  | GotTsdata (Result Http.Error String)
  | Scatterplot_yaxis Int
  | Scatterplot_xaxis Int
  | Polarplot_country Int
  | Timeseries_1 Int
  | Timeseries_2 Int
  | Timeseries_cat Int
  | Click_Scat Int



type alias WorldHappData = 
    { data : List Country_2021,
      ts_data : List Ts_data,
      y_axis : String,
      x_axis : String,
      polar_country : String,
      line_1 : String,
      line_2 : String,
      ts_cat : String
    }


type alias Country_2021 =
    { country_name : String
    , regional_indicator : String
    , ladder_score :  Float
    , se_ladder :  Float
    , u_whisker :  Float
    , l_whisker :  Float
    , lg_gdp_pc :  Float
    , social_support :  Float
    , life_expectancy :  Float
    , freedom_lc :  Float
    , generosity :  Float
    , pc_corruption :  Float
    }


type alias Ts_data = 
      { country_name : String
    -- add country indicator later
    , year : Float
    , ladder_score :  Float
    , lg_gdp_pc :  Float
    , social_support :  Float
    , life_expectancy :  Float
    , freedom_lc :  Float
    , generosity :  Float
    , pc_corruption :  Float
    , positive_affect : Float
    , negative_affect : Float 
    }


id_to_ctry_ts : Int -> String
id_to_ctry_ts id = 
      case id of
        1 -> "Afghanistan"
        2 -> "Albania"
        3 -> "Algeria"
        4 -> "Argentina"
        5 -> "Armenia"
        6 -> "Australia"
        7 -> "Austria"
        8 -> "Azerbaijan"
        9 -> "Bahrain"
        10 -> "Bangladesh"
        11 -> "Belarus"
        12 -> "Belgium"
        13 -> "Benin"
        14 -> "Bolivia"
        15 -> "Bosnia and Herzegovina"
        16 -> "Botswana"
        17 -> "Brazil"
        18 -> "Bulgaria"
        19 -> "Burkina Faso"
        20 -> "Burundi"
        21 -> "Cambodia"
        22 -> "Cameroon"
        23 -> "Canada"
        24 -> "Chad"
        25 -> "Chile"
        27 -> "Colombia"
        28 -> "Comoros"
        29 -> "Congo (Brazzaville)"
        30 -> "Costa Rica"
        31 -> "Croatia"
        32 -> "Cyprus"
        33 -> "Czech Republic"
        34 -> "Denmark"
        35 -> "Dominican Republic"
        36 -> "Ecuador"
        37 -> "Egypt"
        38 -> "El Salvador"
        39 -> "Estonia"
        40 -> "Ethiopia"
        41 -> "Finland"
        42 -> "France"
        43 -> "Gabon"
        44 -> "Gambia"
        45 -> "Georgia"
        46 -> "Germany"
        47 -> "Ghana"
        48 -> "Greece"
        49 -> "Guatemala"
        50 -> "Guinea"
        51 -> "Haiti"
        52 -> "Honduras"
        54 -> "Hungary"
        55 -> "Iceland"
        56 -> "India"
        57 -> "Indonesia"
        58 -> "Iran"
        59 -> "Iraq"
        60 -> "Ireland"
        61 -> "Israel"
        62 -> "Italy"
        63 -> "Ivory Coast"
        64 -> "Jamaica"
        65 -> "Japan"
        66 -> "Jordan"
        67 -> "Kazakhstan"
        68 -> "Kenya"
        70 -> "Kuwait"
        71 -> "Kyrgyzstan"
        72 -> "Laos"
        73 -> "Latvia"
        74 -> "Lebanon"
        75 -> "Lesotho"
        76 -> "Liberia"
        77 -> "Libya"
        78 -> "Lithuania"
        79 -> "Luxembourg"
        80 -> "Madagascar"
        81 -> "Malawi"
        82 -> "Malaysia"
        84 -> "Mali"
        85 -> "Malta"
        86 -> "Mauritania"
        87 -> "Mauritius"
        88 -> "Mexico"
        89 -> "Moldova"
        90 -> "Mongolia"
        91 -> "Montenegro"
        92 -> "Morocco"
        93 -> "Mozambique"
        94 -> "Myanmar"
        95 -> "Namibia"
        96 -> "Nepal"
        97 -> "Netherlands"
        98 -> "New Zealand"
        99 -> "Nicaragua"
        100 -> "Niger"
        101 -> "Nigeria"
        103 -> "North Macedonia"
        104 -> "Norway"
        105 -> "Pakistan"
        106 -> "Palestinian Territories"
        107 -> "Panama"
        108 -> "Paraguay"
        109 -> "Peru"
        110 -> "Philippines"
        111 -> "Poland"
        112 -> "Portugal"
        113 -> "Romania"
        114 -> "Russia"
        115 -> "Rwanda"
        116 -> "Saudi Arabia"
        117 -> "Senegal"
        118 -> "Serbia"
        119 -> "Sierra Leone"
        120 -> "Singapore"
        121 -> "Slovakia"
        122 -> "Slovenia"
        123 -> "South Africa"
        124 -> "South Korea"
        125 -> "Spain"
        126 -> "Sri Lanka"
        127 -> "Swaziland"
        128 -> "Sweden"
        129 -> "Switzerland"
        130 -> "Taiwan Province of China"
        131 -> "Tajikistan"
        132 -> "Tanzania"
        133 -> "Thailand"
        134 -> "Togo"
        135 -> "Tunisia"
        136 -> "Turkey"
        138 -> "Uganda"
        139 -> "Ukraine"
        140 -> "United Arab Emirates"
        141 -> "United Kingdom"
        142 -> "United States"
        143 -> "Uruguay"
        144 -> "Uzbekistan"
        145 -> "Venezuela"
        146 -> "Vietnam"
        147 -> "Yemen"
        148 -> "Zambia"
        149 -> "Zimbabwe"
        _  -> " "

countryTsToid : String -> String
countryTsToid name = 
    case name of
        "Afghanistan" -> "1"
        "Albania" -> "2"
        "Algeria" -> "3"
        "Argentina" -> "4"
        "Armenia" -> "5"
        "Australia" -> "6"
        "Austria" -> "7"
        "Azerbaijan" -> "8"
        "Bahrain" -> "9"
        "Bangladesh" -> "10"
        "Belarus" -> "11"
        "Belgium" -> "12"
        "Benin" -> "13"
        "Bolivia" -> "14"
        "Bosnia and Herzegovina" -> "15"
        "Botswana" -> "16"
        "Brazil" -> "17"
        "Bulgaria" -> "18"
        "Burkina Faso" -> "19"
        "Burundi" -> "20"
        "Cambodia" -> "21"
        "Cameroon" -> "22"
        "Canada" -> "23"
        "Chad" -> "24"
        "Chile" -> "25"
        "Colombia" -> "27"
        "Comoros" -> "28"
        "Congo (Brazzaville)" -> "29"
        "Costa Rica" -> "30"
        "Croatia" -> "31"
        "Cyprus" -> "32"
        "Czech Republic" -> "33"
        "Denmark" -> "34"
        "Dominican Republic" -> "35"
        "Ecuador" -> "36"
        "Egypt" -> "37"
        "El Salvador" -> "38"
        "Estonia" -> "39"
        "Ethiopia" -> "40"
        "Finland" -> "41"
        "France" -> "42"
        "Gabon" -> "43"
        "Gambia" -> "44"
        "Georgia" -> "45"
        "Germany" -> "46"
        "Ghana" -> "47"
        "Greece" -> "48"
        "Guatemala" -> "49"
        "Guinea" -> "50"
        "Haiti" -> "51"
        "Honduras" -> "52"
        "Hungary" -> "54"
        "Iceland" -> "55"
        "India" -> "56"
        "Indonesia" -> "57"
        "Iran" -> "58"
        "Iraq" -> "59"
        "Ireland" -> "60"
        "Israel" -> "61"
        "Italy" -> "62"
        "Ivory Coast" -> "63"
        "Jamaica" -> "64"
        "Japan" -> "65"
        "Jordan" -> "66"
        "Kazakhstan" -> "67"
        "Kenya" -> "68"
        "Kuwait" -> "70"
        "Kyrgyzstan" -> "71"
        "Laos" -> "72"
        "Latvia" -> "73"
        "Lebanon" -> "74"
        "Lesotho" -> "75"
        "Liberia" -> "76"
        "Libya" -> "77"
        "Lithuania" -> "78"
        "Luxembourg" -> "79"
        "Madagascar" -> "80"
        "Malawi" -> "81"
        "Malaysia" -> "82"
        "Mali" -> "84"
        "Malta" -> "85"
        "Mauritania" -> "86"
        "Mauritius" -> "87"
        "Mexico" -> "88"
        "Moldova" -> "89"
        "Mongolia" -> "90"
        "Montenegro" -> "91"
        "Morocco" -> "92"
        "Mozambique" -> "93"
        "Myanmar" -> "94"
        "Namibia" -> "95"
        "Nepal" -> "96"
        "Netherlands" -> "97"
        "New Zealand" -> "98"
        "Nicaragua" -> "99"
        "Niger" -> "100"
        "Nigeria" -> "101"
        "North Macedonia" -> "103"
        "Norway" -> "104"
        "Pakistan" -> "105"
        "Palestinian Territories" -> "106"
        "Panama" -> "107"
        "Paraguay" -> "108"
        "Peru" -> "109"
        "Philippines" -> "110"
        "Poland" -> "111"
        "Portugal" -> "112"
        "Romania" -> "113"
        "Russia" -> "114"
        "Rwanda" -> "115"
        "Saudi Arabia" -> "116"
        "Senegal" -> "117"
        "Serbia" -> "118"
        "Sierra Leone" -> "119"
        "Singapore" -> "120"
        "Slovakia" -> "121"
        "Slovenia" -> "122"
        "South Africa" -> "123"
        "South Korea" -> "124"
        "Spain" -> "125"
        "Sri Lanka" -> "126"
        "Swaziland" -> "127"
        "Sweden" -> "128"
        "Switzerland" -> "129"
        "Taiwan Province of China" -> "130"
        "Tajikistan" -> "131"
        "Tanzania" -> "132"
        "Thailand" -> "133"
        "Togo" -> "134"
        "Tunisia" -> "135"
        "Turkey" -> "136"
        "Uganda" -> "138"
        "Ukraine" -> "139"
        "United Arab Emirates" -> "140"
        "United Kingdom" -> "141"
        "United States" -> "142"
        "Uruguay" -> "143"
        "Uzbekistan" -> "144"
        "Venezuela" -> "145"
        "Vietnam" -> "146"
        "Yemen" -> "147"
        "Zambia" -> "148"
        "Zimbabwe" -> "149"
        _ -> " "


idToCountryPolar : Int -> String
idToCountryPolar id = 
      case id of
        1 -> "Afghanistan"
        2 -> "Albania"
        3 -> "Algeria"
        4 -> "Argentina"
        5 -> "Armenia"
        6 -> "Australia"
        7 -> "Austria"
        8 -> "Azerbaijan"
        9 -> "Bahrain"
        10 -> "Bangladesh"
        11 -> "Belarus"
        12 -> "Belgium"
        13 -> "Benin"
        14 -> "Bolivia"
        15 -> "Bosnia and Herzegovina"
        16 -> "Botswana"
        17 -> "Brazil"
        18 -> "Bulgaria"
        19 -> "Burkina Faso"
        20 -> "Burundi"
        21 -> "Cambodia"
        22 -> "Cameroon"
        23 -> "Canada"
        24 -> "Chad"
        25 -> "Chile"
        26 -> "China"
        27 -> "Colombia"
        28 -> "Comoros"
        29 -> "Congo (Brazzaville)"
        30 -> "Costa Rica"
        31 -> "Croatia"
        32 -> "Cyprus"
        33 -> "Czech Republic"
        34 -> "Denmark"
        35 -> "Dominican Republic"
        36 -> "Ecuador"
        37 -> "Egypt"
        38 -> "El Salvador"
        39 -> "Estonia"
        40 -> "Ethiopia"
        41 -> "Finland"
        42 -> "France"
        43 -> "Gabon"
        44 -> "Gambia"
        45 -> "Georgia"
        46 -> "Germany"
        47 -> "Ghana"
        48 -> "Greece"
        49 -> "Guatemala"
        50 -> "Guinea"
        51 -> "Haiti"
        52 -> "Honduras"
        53 -> "Hong Kong S.A.R. of China"
        54 -> "Hungary"
        55 -> "Iceland"
        56 -> "India"
        57 -> "Indonesia"
        58 -> "Iran"
        59 -> "Iraq"
        60 -> "Ireland"
        61 -> "Israel"
        62 -> "Italy"
        63 -> "Ivory Coast"
        64 -> "Jamaica"
        65 -> "Japan"
        66 -> "Jordan"
        67 -> "Kazakhstan"
        68 -> "Kenya"
        69 -> "Kosovo"
        70 -> "Kuwait"
        71 -> "Kyrgyzstan"
        72 -> "Laos"
        73 -> "Latvia"
        74 -> "Lebanon"
        75 -> "Lesotho"
        76 -> "Liberia"
        77 -> "Libya"
        78 -> "Lithuania"
        79 -> "Luxembourg"
        80 -> "Madagascar"
        81 -> "Malawi"
        82 -> "Malaysia"
        83 -> "Maldives"
        84 -> "Mali"
        85 -> "Malta"
        86 -> "Mauritania"
        87 -> "Mauritius"
        88 -> "Mexico"
        89 -> "Moldova"
        90 -> "Mongolia"
        91 -> "Montenegro"
        92 -> "Morocco"
        93 -> "Mozambique"
        94 -> "Myanmar"
        95 -> "Namibia"
        96 -> "Nepal"
        97 -> "Netherlands"
        98 -> "New Zealand"
        99 -> "Nicaragua"
        100 -> "Niger"
        101 -> "Nigeria"
        102 -> "North Cyprus"
        103 -> "North Macedonia"
        104 -> "Norway"
        105 -> "Pakistan"
        106 -> "Palestinian Territories"
        107 -> "Panama"
        108 -> "Paraguay"
        109 -> "Peru"
        110 -> "Philippines"
        111 -> "Poland"
        112 -> "Portugal"
        113 -> "Romania"
        114 -> "Russia"
        115 -> "Rwanda"
        116 -> "Saudi Arabia"
        117 -> "Senegal"
        118 -> "Serbia"
        119 -> "Sierra Leone"
        120 -> "Singapore"
        121 -> "Slovakia"
        122 -> "Slovenia"
        123 -> "South Africa"
        124 -> "South Korea"
        125 -> "Spain"
        126 -> "Sri Lanka"
        127 -> "Swaziland"
        128 -> "Sweden"
        129 -> "Switzerland"
        130 -> "Taiwan Province of China"
        131 -> "Tajikistan"
        132 -> "Tanzania"
        133 -> "Thailand"
        134 -> "Togo"
        135 -> "Tunisia"
        136 -> "Turkey"
        137 -> "Turkmenistan"
        138 -> "Uganda"
        139 -> "Ukraine"
        140 -> "United Arab Emirates"
        141 -> "United Kingdom"
        142 -> "United States"
        143 -> "Uruguay"
        144 -> "Uzbekistan"
        145 -> "Venezuela"
        146 -> "Vietnam"
        147 -> "Yemen"
        148 -> "Zambia"
        149 -> "Zimbabwe"
        _  -> " "

countryPolarToid : String -> String
countryPolarToid name = 
    case name of
        "Afghanistan" -> "1"
        "Albania" -> "2"
        "Algeria" -> "3"
        "Argentina" -> "4"
        "Armenia" -> "5"
        "Australia" -> "6"
        "Austria" -> "7"
        "Azerbaijan" -> "8"
        "Bahrain" -> "9"
        "Bangladesh" -> "10"
        "Belarus" -> "11"
        "Belgium" -> "12"
        "Benin" -> "13"
        "Bolivia" -> "14"
        "Bosnia and Herzegovina" -> "15"
        "Botswana" -> "16"
        "Brazil" -> "17"
        "Bulgaria" -> "18"
        "Burkina Faso" -> "19"
        "Burundi" -> "20"
        "Cambodia" -> "21"
        "Cameroon" -> "22"
        "Canada" -> "23"
        "Chad" -> "24"
        "Chile" -> "25"
        "China" -> "26"
        "Colombia" -> "27"
        "Comoros" -> "28"
        "Congo (Brazzaville)" -> "29"
        "Costa Rica" -> "30"
        "Croatia" -> "31"
        "Cyprus" -> "32"
        "Czech Republic" -> "33"
        "Denmark" -> "34"
        "Dominican Republic" -> "35"
        "Ecuador" -> "36"
        "Egypt" -> "37"
        "El Salvador" -> "38"
        "Estonia" -> "39"
        "Ethiopia" -> "40"
        "Finland" -> "41"
        "France" -> "42"
        "Gabon" -> "43"
        "Gambia" -> "44"
        "Georgia" -> "45"
        "Germany" -> "46"
        "Ghana" -> "47"
        "Greece" -> "48"
        "Guatemala" -> "49"
        "Guinea" -> "50"
        "Haiti" -> "51"
        "Honduras" -> "52"
        "Hong Kong S.A.R. of China" -> "53"
        "Hungary" -> "54"
        "Iceland" -> "55"
        "India" -> "56"
        "Indonesia" -> "57"
        "Iran" -> "58"
        "Iraq" -> "59"
        "Ireland" -> "60"
        "Israel" -> "61"
        "Italy" -> "62"
        "Ivory Coast" -> "63"
        "Jamaica" -> "64"
        "Japan" -> "65"
        "Jordan" -> "66"
        "Kazakhstan" -> "67"
        "Kenya" -> "68"
        "Kosovo" -> "69"
        "Kuwait" -> "70"
        "Kyrgyzstan" -> "71"
        "Laos" -> "72"
        "Latvia" -> "73"
        "Lebanon" -> "74"
        "Lesotho" -> "75"
        "Liberia" -> "76"
        "Libya" -> "77"
        "Lithuania" -> "78"
        "Luxembourg" -> "79"
        "Madagascar" -> "80"
        "Malawi" -> "81"
        "Malaysia" -> "82"
        "Maldives" -> "83"
        "Mali" -> "84"
        "Malta" -> "85"
        "Mauritania" -> "86"
        "Mauritius" -> "87"
        "Mexico" -> "88"
        "Moldova" -> "89"
        "Mongolia" -> "90"
        "Montenegro" -> "91"
        "Morocco" -> "92"
        "Mozambique" -> "93"
        "Myanmar" -> "94"
        "Namibia" -> "95"
        "Nepal" -> "96"
        "Netherlands" -> "97"
        "New Zealand" -> "98"
        "Nicaragua" -> "99"
        "Niger" -> "100"
        "Nigeria" -> "101"
        "North Cyprus" -> "102"
        "North Macedonia" -> "103"
        "Norway" -> "104"
        "Pakistan" -> "105"
        "Palestinian Territories" -> "106"
        "Panama" -> "107"
        "Paraguay" -> "108"
        "Peru" -> "109"
        "Philippines" -> "110"
        "Poland" -> "111"
        "Portugal" -> "112"
        "Romania" -> "113"
        "Russia" -> "114"
        "Rwanda" -> "115"
        "Saudi Arabia" -> "116"
        "Senegal" -> "117"
        "Serbia" -> "118"
        "Sierra Leone" -> "119"
        "Singapore" -> "120"
        "Slovakia" -> "121"
        "Slovenia" -> "122"
        "South Africa" -> "123"
        "South Korea" -> "124"
        "Spain" -> "125"
        "Sri Lanka" -> "126"
        "Swaziland" -> "127"
        "Sweden" -> "128"
        "Switzerland" -> "129"
        "Taiwan Province of China" -> "130"
        "Tajikistan" -> "131"
        "Tanzania" -> "132"
        "Thailand" -> "133"
        "Togo" -> "134"
        "Tunisia" -> "135"
        "Turkey" -> "136"
        "Turkmenistan" -> "137"
        "Uganda" -> "138"
        "Ukraine" -> "139"
        "United Arab Emirates" -> "140"
        "United Kingdom" -> "141"
        "United States" -> "142"
        "Uruguay" -> "143"
        "Uzbekistan" -> "144"
        "Venezuela" -> "145"
        "Vietnam" -> "146"
        "Yemen" -> "147"
        "Zambia" -> "148"
        "Zimbabwe" -> "149"
        _ -> " "
